version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "les5_2"
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
volumes:
  my_dbdata: